name: Website bug
description: Report a problem with the website (layout, broken link, etc.)
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what’s broken or confusing.
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Page URL (if applicable)
      placeholder: https://affordact.com/...
  - type: input
    id: browser
    attributes:
      label: Browser / device
      placeholder: e.g., iPhone 14 / Safari or Windows / Chrome