#!/usr/bin/env python3
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SECTIONS_DIR = ROOT / "policy" / "sections"
OUT_FILE = ROOT / "policy" / "bill-text.md"
ORDER_FILE = ROOT / "sections.json"

FRONTMATTER_RE = re.compile(r"^\s*---\s*\n.*?\n---\s*\n?", flags=re.S)
H1_RE = re.compile(r"^\s*#\s+(.+?)\s*(?:\n+|$)", flags=re.M)

def natural_key(s):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', s)]

def read_order():
    if ORDER_FILE.exists():
        try:
            data = json.loads(ORDER_FILE.read_text(encoding="utf-8"))
            if isinstance(data, list) and all(isinstance(x, str) for x in data):
                return data
        except Exception:
            pass
    return sorted([p.name for p in SECTIONS_DIR.glob("*.md")], key=natural_key)

def strip_frontmatter(text):
    return FRONTMATTER_RE.sub("", text, count=1)

def pop_first_h1(text):
    m = H1_RE.search(text)
    if not m:
        return None, text
    title = m.group(1).strip()
    # remove that h1 from text
    start, end = m.span()
    new = text[:start] + text[end:]
    return title, new.lstrip()

def prettify(filename):
    return re.sub(r'[_-]+', ' ', filename.replace(".md","")).strip()

def main():
    if not SECTIONS_DIR.exists():
        print("No sections directory found.", file=sys.stderr)
        sys.exit(1)

    order = read_order()
    parts = []
    for filename in order:
        path = SECTIONS_DIR / filename
        if not path.exists():
            print(f"Skip (missing): {path}", file=sys.stderr)
            continue
        raw = path.read_text(encoding="utf-8")
        body = strip_frontmatter(raw).lstrip()
        title, body = pop_first_h1(body)
        if not title:
            title = prettify(filename)

        # One clean H1 + body
        parts.append(f"# {title}\n\n{body.rstrip()}\n")

    header = (
        "<!--- Generated by tools/build_docs.py; do not edit by hand. -->\n"
        "# Affordability Act — Compiled Bill Text\n\n"
        "_Auto-generated from `policy/sections/*.md`._\n\n"
    )
    OUT_FILE.write_text(header + "\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_FILE}")

if __name__ == "__main__":
    main()