#!/usr/bin/env python3
"""
Concatenate policy/sections/*.md into policy/bill-text.md

Order:
1) If sections.json exists at repo root, read it as an array of filenames
   e.g. ["01_Foundations_of_Ownership.md", "02_Housing_and_Land_Use.md"]
2) Otherwise, sort by filename naturally.

Each section header is emitted as: "# <pretty title>"
  - pretty title is taken from the first ATX H1 in the file,
    else derived from the filename.
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SECTIONS_DIR = ROOT / "policy" / "sections"
OUT_FILE = ROOT / "policy" / "bill-text.md"
ORDER_FILE = ROOT / "sections.json"

def natural_key(s):
    import re as _re
    return [int(t) if t.isdigit() else t.lower() for t in _re.split(r'(\d+)', s)]

def read_order():
    if ORDER_FILE.exists():
        try:
            data = json.loads(ORDER_FILE.read_text(encoding="utf-8"))
            if isinstance(data, list) and all(isinstance(x, str) for x in data):
                return data
        except Exception as e:
            print(f"Warning: sections.json parse error: {e}", file=sys.stderr)
    # fallback: natural sort of .md files
    return sorted([p.name for p in SECTIONS_DIR.glob("*.md")], key=natural_key)

def first_h1(text):
    m = re.search(r'^\s*#\s+(.+)$', text, flags=re.M)
    return m.group(1).strip() if m else None

def prettify(name):
    return re.sub(r'[_-]+', ' ', name.replace(".md","")).strip()

def main():
    if not SECTIONS_DIR.exists():
        print("No sections directory found.", file=sys.stderr)
        sys.exit(1)

    order = read_order()
    parts = []
    for filename in order:
        path = SECTIONS_DIR / filename
        if not path.exists():
            print(f"Skip (missing): {path}", file=sys.stderr)
            continue
        text = path.read_text(encoding="utf-8").rstrip() + "\n"
        title = first_h1(text) or prettify(filename)
        parts.append(f"# {title}\n\n{text}\n")

    header = (
        "<!--- Generated by tools/build_docs.py; do not edit by hand. -->\n"
        "# Affordability Act — Compiled Bill Text\n\n"
        "_Auto-generated from `policy/sections/*.md`._\n\n"
    )
    OUT_FILE.write_text(header + "\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT_FILE}")

if __name__ == "__main__":
    main()
