name: Build policy docs

on:
  push:
    paths:
      - 'policy/sections/**'
      - 'tools/**'
      - 'policy/README.md'
      - 'policy/outline.md'
      - '.github/workflows/compile.yml'
  pull_request:
    paths:
      - 'policy/sections/**'
      - 'tools/**'
      - 'policy/README.md'
      - 'policy/outline.md'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Compile master bill
        run: python3 tools/compile_master.py

      - name: Render policy README
        run: python3 tools/render_policy_readme.py

      - name: Update outline
        run: python3 tools/update_outline.py
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Commit outputs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(policy): rebuild bill + README + outline by @${{ github.actor }} [skip ci]"
          file_pattern: |
            policy/bill-text.md
            policy/README.md
            policy/outline.md
